/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ThongKeLopHocPhanDAO;
import javax.swing.*;
import java.util.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import Model.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author nguyenthang
 */
public class ThongKeCacLopHocPhanFrm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ThongKeCacLopHocPhan
     */
    DefaultTableModel tm;
    ThongKeTheoMonHocFrm parent;
    String kyBD;
    String kyKT;
    ThongKeTheoMonHoc tkmh;
    private ArrayList<ThongKeLopHocPhan> ltk;
    private ArrayList<JButton> listChiTiet;
    
    public ThongKeCacLopHocPhanFrm(ThongKeTheoMonHocFrm parent,String kyBD,String kyKT, ThongKeTheoMonHoc tkmh ) {
        this.parent=parent;
        this.kyBD=kyBD;
        this.kyKT=kyKT;
        this.tkmh=tkmh;
        initComponents();
        ltk=new ArrayList<ThongKeLopHocPhan>();
        listChiTiet = new ArrayList<JButton>();
        jLabel11.setText(tkmh.getTenMon().toString());
        jLabel10.setText(tkmh.getKhoa().toString());
        jLabel13.setText(tkmh.getKiBD().toString());
        jLabel14.setText(tkmh.getKiKT().toString());
        jLabel12.setText(tkmh.getTongSoSinhVien().toString());
        btnQuayLai.addActionListener(this);
        ThongKeLopHocPhanDAO tk=new ThongKeLopHocPhanDAO();
        ltk=tk.layThongKeLopHocPhan(kyBD, kyKT, tkmh.getMonID().toString());
        tblResult.setModel(new ResultTableModel());
        TableCellRenderer buttonRenderer = new JTableButtonRenderer();
        tblResult.getColumn("Chi tiết").setCellRenderer(buttonRenderer);
        tblResult.addMouseListener(new JTableButtonMouseListener(tblResult));
        for(int i = 1; i <= ltk.size(); i++){
            JButton add = new JButton("Xem");
            add.addActionListener(this);
            listChiTiet.add(add);
        }
        tblResult.setRowHeight(25);
        TableColumn col = tblResult.getColumnModel().getColumn(0);
        col.setPreferredWidth(10);
        col = tblResult.getColumnModel().getColumn(1);
        col.setPreferredWidth(80);
        col = tblResult.getColumnModel().getColumn(2);
        col.setPreferredWidth(80);
        col = tblResult.getColumnModel().getColumn(3);
        col.setPreferredWidth(20);
        col = tblResult.getColumnModel().getColumn(4);
        col.setPreferredWidth(40);
        col = tblResult.getColumnModel().getColumn(5);
        col.setPreferredWidth(40);
        col = tblResult.getColumnModel().getColumn(6);
        col.setPreferredWidth(30);
        this.setLocation(300,150);
        for(int i = 0; i < 6; i++){
            TableColumnModel columnModel = tblResult.getColumnModel();
            TableColumn column = columnModel.getColumn(i); 
            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.CENTER);
            column.setCellRenderer(renderer);
        }
        ((DefaultTableModel)tblResult.getModel()).fireTableDataChanged();
    };
    
    public void actionPerformed(ActionEvent e){
        JButton btnClicked = (JButton)e.getSource();
        if(btnClicked.equals(btnQuayLai)){
            btnQuayLaiDuocNhan();
            return;
        }
        for(int i = 0; i < ltk.size(); i++){
            if(btnClicked.equals(listChiTiet.get(i))){
                btnChiTietDuocNhan(i);
                return;
            }
        }
    }
    
    private void btnChiTietDuocNhan(int i){
        this.setVisible(false);
        ThongKeLopHocPhan tklhp= new ThongKeLopHocPhan();
        tklhp=ltk.get(i);
        new ChiTietLopHocPhanFrm(this,tklhp).setVisible(true);
    }
    
    private void btnQuayLaiDuocNhan(){
        parent.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        btnQuayLai = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thông tin môn học");

        jLabel2.setText("Tên môn học");

        jLabel3.setText("Tên khoa");

        jLabel4.setText("Tổng số sinh viên");

        jLabel5.setText("Thông tin thống kê");

        jLabel6.setText("Kì bắt đầu");

        jLabel7.setText("Kì kết thúc");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("THỐNG KÊ CÁC LỚP HỌC PHẦN CỦA MÔN HỌC");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        btnQuayLai.setText("Quay lại");

        jLabel10.setText("       ");

        jLabel11.setText("  ");

        jLabel13.setText("  ");

        jLabel14.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(579, 579, 579))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnQuayLai)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(259, 259, 259)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(327, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(233, 233, 233))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuayLai)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables

    class ResultTableModel extends DefaultTableModel{
        private String[] columnNames = {"STT", "Lớp học phần", "Giảng viên", "Sỹ số", "Điểm trung bình", "Tỷ lệ qua môn(%)", "Chi tiết"};
        private final Class<?>[] columnTypes = new Class<?>[] {Integer.class, String.class,String.class, Integer.class, Float.class, Integer.class, JButton.class};
        @Override public int getColumnCount() {
            return 7;
        }
 
        @Override public int getRowCount() {
            return ltk.size();
        }
 
        @Override public String getColumnName(int columnIndex) {
            return columnNames[columnIndex];
        }
 
        @Override public Class<?> getColumnClass(int columnIndex) {
            return columnTypes[columnIndex];
        }
        
        @Override public Object getValueAt(final int rowIndex, final int columnIndex) {
            switch (columnIndex) {
                case 0: 
                    return rowIndex+1;
                case 1: 
                    return ltk.get(rowIndex).getLopHocPhan();
                case 2: 
                    return ltk.get(rowIndex).getGiangVien();
                case 3: 
                    return ltk.get(rowIndex).getSySo();
                case 4: 
                    return ltk.get(rowIndex).getDiemTB();
                case 5: 
                    return ltk.get(rowIndex).getTyLeQuaMon();
                case 6: 
                    return listChiTiet.get(rowIndex);
                default: return "Error";
            }
        } 
    }
}
