/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.LopHocPhanDAO;
import Model.LopHocPhan;
import Model.MonHoc;
import Model.SinhVien;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author ntnhu
 */
public class TimLopFrm extends javax.swing.JFrame implements ActionListener{
    private SinhVien SV;
    private MonHoc MH;
    private ArrayList<LopHocPhan> ListLHP;
    private ArrayList<JButton> ListLC;    
    private ArrayList<LopHocPhan> ListDK;
    DefaultTableModel tm;
    /**
     * Creates new form TimLopFrm
     */
    public TimLopFrm(MonHoc MH, SinhVien SV,ArrayList<LopHocPhan> ListDK) {
        this.SV=SV;
        this.MH = MH;
        this.ListDK=ListDK;
        ListLHP=new ArrayList<>();
        ListLC=new ArrayList<>();
        LopHocPhanDAO lhpDAO=new LopHocPhanDAO();
        this.ListLHP=lhpDAO.TimLopTheoMon(MH);
        initComponents();
        btnQuayLai.addActionListener(this);
        lblMaMon.setText(lblMaMon.getText()+MH.getMaMon());
        lblTenMon.setText(lblTenMon.getText()+MH.getTenMon());
        lblSoTinChi.setText(lblSoTinChi.getText()+MH.getSoTinChi());
        tblResult.setModel(new LopTableModel());
        TableCellRenderer btnRenderer = new JTableButtonRenderer();
        tblResult.getColumn("Lựa chọn").setCellRenderer(btnRenderer);
        tblResult.addMouseListener(new JTableButtonMouseListener(tblResult)); 
        fillTable(ListLHP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMaMon = new javax.swing.JLabel();
        lblTenMon = new javax.swing.JLabel();
        lblSoTinChi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Lựa Chọn Lớp Học Phần");

        lblMaMon.setText("Mã Môn Học : ");

        lblTenMon.setText("Tên Môn Học : ");

        lblSoTinChi.setText("Số Tín Chỉ : ");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Lớp", "Tên Lớp", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        jLabel5.setText("Danh Sách Lớp Học Phần :");

        btnQuayLai.setText("Quay Lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaMon)
                                    .addComponent(lblTenMon)
                                    .addComponent(jLabel5))
                                .addGap(293, 293, 293)
                                .addComponent(lblSoTinChi))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnQuayLai)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaMon)
                    .addComponent(lblSoTinChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenMon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnQuayLai)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnQuayLaiClicked(){
        new TimMonFrm(SV, ListDK).setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    private void fillTable(ArrayList<LopHocPhan> ListLHP){  
        tblResult.setRowHeight(20);
        TableColumn col = tblResult.getColumnModel().getColumn(0);
        col.setPreferredWidth(5);  
        col = tblResult.getColumnModel().getColumn(1);
        col.setPreferredWidth(15);     
        col = tblResult.getColumnModel().getColumn(2);
        col.setPreferredWidth(150);  
        col = tblResult.getColumnModel().getColumn(3);
        col.setPreferredWidth(10);   
        col = tblResult.getColumnModel().getColumn(4);
        col.setPreferredWidth(10);       
        for(MonHoc i:ListLHP){
            JButton btn=new JButton("Chọn");
            btn.addActionListener(this);
            ListLC.add(btn);
        }
        for(int i = 0; i < 4; i++){
            TableColumnModel columnModel = tblResult.getColumnModel();
            TableColumn column = columnModel.getColumn(i); 
            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.CENTER);
            column.setCellRenderer(renderer);
        }
        ((DefaultTableModel)tblResult.getModel()).fireTableDataChanged();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaMon;
    private javax.swing.JLabel lblSoTinChi;
    private javax.swing.JLabel lblTenMon;
    private javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton btnClicked =(JButton)e.getSource();
        if(btnClicked.equals(btnQuayLai)){
            btnQuayLaiClicked();
        }
        for(int i=0;i<ListLHP.size();i++){
            if(btnClicked.equals(ListLC.get(i))){
                LopHocPhan ex=ListLHP.get(i);
                if(ex.getDaChon()==ex.getSiSo()){
                    JOptionPane.showMessageDialog(this, "Sĩ số lớp đã đạt tối đa!");
                }
                else{
                    new XemLichFrm(SV, ListLHP.get(tblResult.getSelectedRow()),ListDK).setVisible(true);
                    this.dispose();
                }  
            }
        }
    }
    class LopTableModel extends DefaultTableModel{
        private String[] columnNames = {"STT", "Mã lớp", "Tên lớp", "Trạng thái","Lựa chọn"};
        private final Class<?>[] columnTypes = new Class<?>[] {Integer.class, String.class,String.class, String.class, JButton.class};
        @Override public int getColumnCount() {
            return 5;
        }
 
        @Override public int getRowCount() {
            return ListLHP.size();
        }
 
        @Override public String getColumnName(int columnIndex) {
            return columnNames[columnIndex];
        }
 
        @Override public Class<?> getColumnClass(int columnIndex) {
            return columnTypes[columnIndex];
        }
        
        @Override public Object getValueAt(final int rowIndex, final int columnIndex) {
            switch (columnIndex) {
                case 0: 
                    return rowIndex+1;
                case 1: 
                    return ListLHP.get(rowIndex).getMaLop();
                case 2: 
                    return ListLHP.get(rowIndex).getTen();
                case 3:
                    return ListLHP.get(rowIndex).getDaChon()+" / "+ListLHP.get(rowIndex).getSiSo();
                case 4: 
                    return ListLC.get(rowIndex);
                default: return "Error";
            }
        } 
    }    
}
