/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.GiangVien;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author TaDuyHieu
 */
public class TrangChuGiangVienFrm extends javax.swing.JFrame implements ActionListener{
    private GiangVien GV;

    /**
     * Creates new form TrangChuGiangVienFrm
     */
    public TrangChuGiangVienFrm(GiangVien GV) {
        initComponents();
        this.GV = GV;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        btnNhapDiem.addActionListener(this);
        btnXemTKB.addActionListener(this);
        btnInDSLHP.addActionListener(this);
        btnQuayLai.addActionListener(this);
        this.setLocation(300,150);
    }
    
    public TrangChuGiangVienFrm() {
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelGV = new javax.swing.JLabel();
        btnNhapDiem = new javax.swing.JButton();
        btnXemTKB = new javax.swing.JButton();
        btnInDSLHP = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelGV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelGV.setForeground(new java.awt.Color(0, 0, 102));
        labelGV.setText("TRANG CHỦ GIẢNG VIÊN");

        btnNhapDiem.setText("Nhập điểm");

        btnXemTKB.setText("Xem TKB");

        btnInDSLHP.setText("In danh sách lớp học phần");

        btnQuayLai.setText("Đăng xuất");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnQuayLai)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(labelGV, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInDSLHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNhapDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXemTKB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelGV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnNhapDiem)
                .addGap(18, 18, 18)
                .addComponent(btnXemTKB)
                .addGap(18, 18, 18)
                .addComponent(btnInDSLHP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnQuayLai)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInDSLHP;
    private javax.swing.JButton btnNhapDiem;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnXemTKB;
    private javax.swing.JLabel labelGV;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton btnClicked = (JButton)e.getSource();
        if(btnClicked.equals(btnNhapDiem)){
            this.setVisible(false);
            (new TimMonTheoKy(this.GV, this)).setVisible(true);
            return;
        }
        if(btnClicked.equals(btnQuayLai)){
            new DangNhapFrm().setVisible(true);
            this.dispose();
            return;
        }
//        if(btnClicked.equals(btnXemTKB)){
//            this.setVisible(false);
//            (new ThongKeFrm(this)).setVisible(true);
//            return;
//        }
//        if(btnClicked.equals(btnInDSLHP)){
//            this.setVisible(false);
//            (new ThongKeFrm(this)).setVisible(true);
//            return;
//        }
    }
}
