/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.GiangVienDAO;
import Control.KipHocDAO;
import Control.LichGiangDayDAO;
import Control.MonHocDAO;
import Control.NguoiDungDAO;
import Control.PhongHocDAO;
import Model.GiangVien;
import Model.KipHoc;
import Model.LichGiangDay;
import Model.LopHocPhan;
import Model.MonHoc;
import Model.NguoiDung;
import Model.PhongHoc;
import Model.SinhVien;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ntnhu
 */
public class XemLichFrm extends javax.swing.JFrame {
    private SinhVien SV;
    private LopHocPhan LHP;
    private ArrayList<LichGiangDay> ListLGD;
    private ArrayList<LopHocPhan> ListDK;
    DefaultTableModel tm;
    /**
     * Creates new form XemLichFrm
     */
    public XemLichFrm() {
        initComponents();
    }

    public XemLichFrm(SinhVien SV, LopHocPhan LHP,ArrayList<LopHocPhan> ListDK) {
        this.SV = SV;
        this.LHP = LHP;
        this.ListDK=ListDK;
        initComponents();
        jLabel2.setText(jLabel2.getText()+LHP.getMaLop());
        jLabel3.setText(jLabel3.getText()+LHP.getTen());
        LichGiangDayDAO lgdDAO=new LichGiangDayDAO();
        ListLGD=lgdDAO.TimLichTheoIdLop(LHP.getLopHocPhanId());
        fillTable(ListLGD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Thông Tin Lịch Giảng Dạy");

        jLabel2.setText("Mã Lớp Học Phần : ");

        jLabel3.setText("Tên Lớp Học Phần : ");

        jLabel4.setText("Chi Tiết Lịch Giảng Dạy:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tuần Bắt Đầu", "Tuần Kết Thúc", "Thời Gian", "Thứ", "Phòng Học", "Giảng Viên"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Quay Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Đăng Ký");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton2)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MonHoc MH=new MonHocDAO().TimMonHocTheoId(LHP.getMonHocId());
        new TimLopFrm(MH, SV, ListDK).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(CheckTrungLich()==false){
            JOptionPane.showMessageDialog(this, "Trùng Lịch");
            MonHoc MH=new MonHocDAO().TimMonHocTheoId(LHP.getMonHocId());
            new TimLopFrm(MH, SV, ListDK).setVisible(true);
            this.dispose();
        }
        else{
            ListDK.add(LHP);
            new DangKyTinChiFrm(SV, ListDK).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemLichFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemLichFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemLichFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemLichFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemLichFrm().setVisible(true);
            }
        });
    }
    public void fillTable(ArrayList<LichGiangDay> ListLGD){
        int stt=0;
        tm=(DefaultTableModel)jTable1.getModel();
        tm.setRowCount(ListLGD.size());
        for(LichGiangDay i:ListLGD){
            tm.setValueAt(i.getTuanBatDau(), stt, 0);
            tm.setValueAt(i.getTuanKetThuc(), stt, 1);
            KipHoc KH=new KipHocDAO().TimKipHocTheoId(i.getTblKipHocId());
            tm.setValueAt(KH.getGioBatDau()+"h - "+KH.getGioKetThuc()+"h", stt, 2);
            tm.setValueAt(KH.getThu(), stt, 3);
            PhongHoc PH=new PhongHocDAO().TimPhongHocTheoId(i.getTblPhongHocId());
            tm.setValueAt(PH.getTenPhong(), stt, 4);
            GiangVien GV=new GiangVienDAO().TimGiangVienTheoId(i.getTblGiangVientblNguoiDungId());
            NguoiDung nd=new NguoiDungDAO().TimNguoiDungTheoId(GV.getTblNguoiDungId());
            tm.setValueAt(nd.getHoTen(), stt, 5);
            stt++;
        }
    }
    private boolean CheckTrungLich(){
        ArrayList<LichGiangDay> tempListLGD=new ArrayList<>();
        for(LopHocPhan lhp : ListDK)tempListLGD.addAll(new LichGiangDayDAO().TimLichTheoIdLop(lhp.getLopHocPhanId()));
        for(LichGiangDay templgd : tempListLGD){
            for(LichGiangDay lgd : ListLGD){
//                System.out.println("tempbd-"+templgd.getTuanBatDau()+"-tempkt"+templgd.getTuanKetThuc()
//                +"-bd-"+lgd.getTuanBatDau()+"-kt-"+lgd.getTuanKetThuc());
                if(templgd.getTuanBatDau()>lgd.getTuanKetThuc()||templgd.getTuanKetThuc()<lgd.getTuanBatDau()){
                    
                }
                else{
//                    System.out.println(templgd.getTblKipHocId()+" "+lgd.getTblKipHocId());
                    if(templgd.getTblKipHocId()==lgd.getTblKipHocId()){
                        return false;
                    }
                }
            }
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
